version: "3.8"

services:
  mongo:
    image: mongo:7.0
    container_name: continuum-mongo
    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - ../continuum-dbvolume:/data/db

    environment:
      MONGO_INITDB_DATABASE: continuum

    command: ["mongod", "--bind_ip_all"]
